#!/bin/bash

# ----------------------- #
# BSPWM CONFIGURATION     #
# ----------------------- #

if [ $(xrandr -q | grep "HDMI-1 connected" | cut -d ' ' -f1) = "HDMI-1" ]; then
	xrandr --output HDMI-1 --primary --auto --rotate normal --output eDP-1 --auto --rotate normal
	xrandr --output eDP-1 --auto --rotate normal --right-of HDMI-1
else
	xrandr --output eDP-1 --primary --auto --rotate normal
fi

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0

## BSPWM CONFIG ========================== #
~/.config/bspwm/scripts/bspcConfig

## BSPWM RULES ========================== #

~/.config/bspwm/scripts/bspcRule

## AUTOSTART PROGRAMS ======================== #
~/.config/bspwm/scripts/bspcPrograms "1"

## BSPWM COLORS ======================== #
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color3"
